export const APP_STATE = {
    WALLET_WITHOUT_STATE : -1,
    WALLET_NOT_INITIALIZED : 0,
    WALLET_INITIALIZED : 1,
    WALLET_RESTORE : 2,
    WALLET_LOCKED : 3,
    WALLET_UNLOCKED : 4,
    WALLET_TRANSFERS_IN_QUEUE : 5,
}

