export const APP_STATE = {
  WALLET_WITHOUT_STATE: -1,
  WALLET_NOT_INITIALIZED: 0,
  WALLET_INITIALIZED: 1,
  WALLET_RESTORE: 2,
  WALLET_LOCKED: 3,
  WALLET_UNLOCKED: 4,
  WALLET_REQUEST_IN_QUEUE_WITH_USER_INTERACTION: 5,
  WALLET_REQUEST_PERMISSION_OF_CONNECTION: 6
}
