export const APP_STATE = {
  WALLET_WITHOUT_STATE: -1,
  WALLET_NOT_INITIALIZED: 0,
  WALLET_INITIALIZED: 1,
  WALLET_RESTORE: 2,
  WALLET_LOCKED: 3,
  WALLET_UNLOCKED: 4,
  WALLET_REQUEST_IN_QUEUE_WITH_USER_INTERACTION: 5,
  WALLET_REQUEST_PERMISSION_OF_CONNECTION: 6
}

export const STATE_NAME = {
  '-1': 'WALLET_WITHOUT_STATE',
  '0': 'WALLET_NOT_INITIALIZED',
  '1': 'WALLET_INITIALIZED',
  '2': 'WALLET_RESTORE',
  '3': 'WALLET_LOCKED',
  '4': 'WALLET_UNLOCKED',
  '5': 'WALLET_REQUEST_IN_QUEUE_WITH_USER_INTERACTION',
  '6': 'WALLET_REQUEST_PERMISSION_OF_CONNECTION'
}
